spring.application.name=sam

# Database
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sam}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# OpenAPI / Swagger
springdoc.swagger-ui.url=/openapi.yaml

# Console
spring.output.ansi.enabled=ALWAYS

# Scheduler
sam.screening.fixed-delay-ms=10000
sam.screening.initial-delay-ms=10000
